name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      #output de dados de contexto e metadados do github com ${{}}. pode ser variaveis de ambiente, etc
      - name: output github context
        run: echo "${{ toJSON(github) }}"