name: Test React Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: REcupera codigo do repositorio
        uses: actions/checkout@v3

      - name: instala o nodejs com versão 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: instala dependencias e executa comando com run
        run: npm ci

      - name: Executa os testes do projeto
        run: npm test
  deploy: 
  #needs e utilizado para criar uma dependencia. o deploy só vai funcionar quando o job anterior for finalizado 
  #pode ser usado como [] para esperar varios processos
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Recupera codigo do repositorio
        uses: actions/checkout@v3

      - name: instala o nodejs com versão 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: instala dependencias e executa comando com run
        run: npm ci

      - name: build do projeto
        run: npm run build

      - name: deploy
        run: echo "deploy apenas para teste..."